name: youtube_downloader_flutter
description: Downloads videos from youtube with ease!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  youtube_explode_dart: ^2.2.1
  stream_transform: ^2.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.7
  window_manager: ^0.4.2
  win32: ^5.5.4
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0
  json_annotation: ^4.0.1
  url_launcher: ^6.0.9
  intl: ^0.19.0
  ffmpeg_kit_flutter: ^6.0.3
  permission_handler: ^11.3.1
  open_file: ^3.2.1
  file_picker: ^8.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  device_info_plus: ^10.1.2

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13

dependency_overrides:
  freezed_annotation: ^2.4.4


flutter:
  uses-material-design: true
  generate: true
